import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import { GlobalStyles } from "./globals";

import "@mantine/core/styles.css";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript/>
      </head>
      <body className={nunito.className}>
        <MantineProvider>
          <GlobalStyles />
          <main>{children}</main>
        </MantineProvider>
      </body>
    </html>
  );
}
