import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { MantineProvider, ColorSchemeScript, MantineColorsTuple } from "@mantine/core";
import { GlobalStyles } from "./globals";

import "@mantine/core/styles.css";
import StyledComponentsRegistry from "./lib/styled-components/registry";
import { theme } from "@/theme/theme";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript/>
      </head>
      <body className={nunito.className}>
        <MantineProvider defaultColorScheme="dark" theme={theme}>
          <StyledComponentsRegistry>
            <GlobalStyles />
            <main>{children}</main>
          </StyledComponentsRegistry>
        </MantineProvider>
      </body>
    </html>
  );
}
